### PR TITLE
use bootstrap on cdn to speedup

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by devigned** [comment]
Please have a look at the jekyll branch. These changes are great for the current site, though when moving to the jekyll based site, the assets will all be minified and uglified together.

Something like:
```html
  <link rel="stylesheet" href="/assets/app-5fd2662d1edc7782e0f2c5f2175a11a0.css">
  <script src="/assets/app-1876d1adc95a6d78c1971d25b0e08c98.js"></script>
```
These files could benefit from a cdn with a longer cache timeout (github.io: Cache-Control:max-age=600).

I'm going to close this pull request, because it targets code that has changed. The original reason for the pull request is valid and the fix is the correct one. 

Thank you. Please consider future pull requests.

**Comment by PeterDaveHello** [comment]
Why not just modify this PR?

**Comment by devigned** [comment]
B/c I think you are going to run into more issues... A cdn will need to be setup to host the generated assets as they are the concatenated, minified and ugilified version of all js and css needed for the site.

That being said, unless you want to create that cdn instance, provide the host name to Jekyll and then let us run on that cdn indefinitely, it's going to take some msft cdn provisioning and setup.

The good part, is that Jekyll provides this functionality.

**Comment by PeterDaveHello** [comment]
oh okay, thanks for your explain :+1:

**Pull request closed without merging**
