### PR TITLE
Transform site from html to Jekyll

### PR DESCRIPTION
**Pull request by devigned**
## Transform site from html to Jekyll

- move site to jekyll
- add some helpers for publishing, readme and license
- better instructions for usage and contribution

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Looks good - have any folks looked through and done an exhaustive CR?

**Comment by devigned** [comment]
Yours are probably the first set of eyes on this change set. I've tried to add enough getting started info to help anyone that was interested. How would you like to proceed?

**Comment by jeffwilcox** [comment]
@devigned I'm thinking it is time for me to hand the baton on to you regarding this microsite. I typically don't think exhaustive CRs are productive for things like this and I'm slammed as it is ;-)

**Comment by jeffwilcox** [comment]
@devigned oh and you already have write permissions :) I'd say just accept this PR if you're happy with it!

**Comment by devigned** [comment]
Thank you, @jeffwilcox. I'll keep your fine work in good repair. Cheers!

**Comment by devigned** [comment]
@jeffwilcox would you be so kind to change the default branch over to jekyll? I'd like to provide the source code as the default branch, then have master contain the generated html. That would provide a cue to any contributors that they should contribute to the Jekyll branch.

**Comment by jeffwilcox** [comment]
@devigned done

**Pull request merged**
