### PR TITLE
fix reference to PowerShell repository

### PR DESCRIPTION
**Pull request by sebagomez**

### CODE REVIEW

**Comment by sebagomez** [comment]
sooo, am I a contributor? :)

**Comment by jeffwilcox** [comment]
In what regards? We're always happy to take documentation/site contributions here!

**Comment by sebagomez** [comment]
Just kidding about the thanks page.
Looking forward to start working with xplat-cli... Will contribute there, when needed of course

Sent from my Windows Phone
________________________________

**Comment by sebagomez** [comment]
Just kidding about the thanks page.
Looking forward to start working with xplat-cli... Will contribute there, when needed of course

Sent from my Windows Phone

-----Original Message-----

**Comment by jeffwilcox** [comment]
Oh I see :-)

Note that to contribute to the software side of things, there is a CLA requirement. If you see yourself contributing there soon, it might be good to fill that out online. When you submit a PR to one of the source projects, it'll have details.

**Comment by sebagomez** [comment]
Good to know
Thanks

Sent from my Windows Phone
________________________________

**Pull request merged**
